### ISSUE TITLE
sidecar: Unable to connect to Azure storage on 0.4.0

### ISSUE THREAD

**Issue by sbocz** [improbable-eng/thanos#1158]
**Thanos, Prometheus and Golang version used**

Docker image: improbable/thanos:v0.4.0

**What happened**

Thanos sidecar container is having errors resolving Azure storage endpoint when updating image to 0.4.0 from 0.3.1.

**What you expected to happen**

No errors, as nothing else changed.

**How to reproduce it (as minimally and precisely as possible)**:

Run prometheus with a sidecar container

```yaml
- image: improbable/thanos:v0.4.0
  name: thanos-sidecar
  args:
  - sidecar
  - --prometheus.url=http://127.0.0.1:9090/
  - --tsdb.path=/prometheus
  - --cluster.disable
  - --grpc-address=[$(POD_IP)]:10901
  - --objstore.config=$(OBJSTORE_CONFIG)
  env:
  - name: POD_IP
    valueFrom:
      fieldRef:
        apiVersion: v1
        fieldPath: status.podIP
  - name: OBJSTORE_CONFIG
    valueFrom:
      secretKeyRef:
        key: thanos.yaml
        name: thanos-objstore-config
  ports:
  - containerPort: 10902
    name: http
    protocol: TCP
  - containerPort: 10901
    name: grpc
    protocol: TCP
  - containerPort: 10900
    name: cluster
    protocol: TCP
```
```yaml
apiVersion: v1
kind: Secret
metadata:
  name: thanos-objstore-config
data:
  thanos.yaml: 
# Data shown here is not literal value
type: AZURE
config:
  storage_account: "thanosaccount"
  storage_account_key: "key"
  container: "thanoscontainer"
  endpoint: "https://thanosaccount.blob.core.windows.net/"
```

**Full logs to relevant components**

<details>Sidecar Logs
<p>

```
level=info ts=2019-05-17T06:21:53.355636937Z caller=flags.go:87 msg="gossip is disabled"
level=info ts=2019-05-17T06:21:53.355912237Z caller=main.go:257 component=sidecar msg="disabled TLS, key and cert must be set to enable"
level=info ts=2019-05-17T06:21:53.355950837Z caller=factory.go:39 msg="loading bucket configuration"
sidecar command failed: create AZURE client: Azure API return unexpected error: *pipeline.pcError
: -> github.com/Azure/azure-pipeline-go/pipeline.newDefaultHTTPClientFactory.func1.1, /go/pkg/mod/github.com/!azure/azure-pipeline-go@v0.1.8/pipeline/core.go:234
HTTP request failed

Put https://thanosaccount.https://thanosaccount.blob.core.windows.net/thanoscontainer?restype=container&timeout=61: dial tcp: lookup thanosaccount.https on 10.0.0.10:53: no such host
```

</p>
</details>

**Anything else we need to know**

This looks like an issue in the way the configuration is parsed to get the storage endpoint to call.

@vglafirov

**Comment by sbocz** [comment]
I _think_ the issue might be here https://github.com/improbable-eng/thanos/blob/master/pkg/objstore/azure/helpers.go#L33. Sorry I've never used golang before

**Comment by sbocz** [comment]
I updated from 
```yaml
config:
  storage_account: "thanosaccount"
  storage_account_key: "KEY"
  container: "thanoscontainer"
  endpoint: "https://thanosaccount.blob.core.windows.net/"
```

to 

```yaml
config:
  storage_account: "thanosaccount"
  storage_account_key: "KEY"
  container: "thanoscontainer"
  endpoint: ""
```

And things are working now. I'm honestly not sure why I was using `endpoint: "https://thanosaccount.blob.core.windows.net/"` in my old setup. Perhaps I'll update the docs to show what each field is for.
