### ISSUE TITLE
query: Querier stores are down, but no errors in sidecars or store gateway.

### ISSUE THREAD

**Issue by sbocz** [improbable-eng/thanos#1171]
**Thanos, Prometheus and Golang version used**

thanos, version 0.4.0 (branch: HEAD, revision: a676095877e7a87576b0f7776fccd4b3f8b65188)
  build user:       circleci@9a3cf9118f1e
  build date:       20190504-09:35:43
  go version:       go1.12.4

prometheus, version 2.9.1 (branch: HEAD, revision: ad71f2785fc321092948e33706b04f3150eee44f)
  build user:       root@09f919068df4
  build date:       20190416-17:50:04
  go version:       go1.12.4

**What happened**

Querier stores page shows that all stores are down with error `rpc error: code = DeadlineExceeded desc = context deadline exceeded`.

![image](https://user-images.githubusercontent.com/10420761/58204352-f8093a80-7c90-11e9-96c6-c4ea28cad862.png)

The sidecar and store gateway appear to be healthy and working according to their logs.

**How to reproduce it (as minimally and precisely as possible)**:

Deploying all components to AKS v1.12.7

**Sidecar setup**

Prometheus Statefulset
2 replicas exist
<details>
<p>

```yaml
...
    containers:
    - args:
      - sidecar
      - --prometheus.url=http://127.0.0.1:9090/
      - --tsdb.path=/prometheus
      - --cluster.address=[$(POD_IP)]:10900
      - --grpc-address=[$(POD_IP)]:10901
      - --objstore.config=$(OBJSTORE_CONFIG)
      env:
      - name: OBJSTORE_CONFIG
        valueFrom:
          secretKeyRef:
            key: thanos.yaml
            name: thanos-objstore-config
      image: improbable/thanos:v0.4.0
      name: thanos-sidecar
      ports:
      - containerPort: 10902
        name: http
        protocol: TCP
      - containerPort: 10901
        name: grpc
        protocol: TCP
      - containerPort: 10900
        name: cluster
        protocol: TCP
```

</p>
</details>

Service:
<details>
<p>

Two services (`thanos-sidecar-0` and `thanos-sidecar-1`) exist that are specifically targetted at each prometheus replica
```yaml
apiVersion: v1
kind: Service
metadata:
  labels:
    app: prometheus
  name: thanos-sidecar-0
  namespace: monitoring
spec:
  ports:
  - port: 10901
    protocol: TCP
    targetPort: grpc
    name: grpc
  selector:
    statefulset.kubernetes.io/pod-name: prometheus-prometheus-operator-prometheus-0
```

</p>
</details>

**Thanos store setup**

Deployment
<details>
<p>

```yaml
...
  containers:
  - args:
    - store
    - --log.level=debug
    - --data-dir=/data
    - --cluster.disable
    - --index-cache-size=500MB
    - --chunk-pool-size=500MB
    - --objstore.config=$(OBJSTORE_CONFIG)
    env:
    - name: OBJSTORE_CONFIG
      valueFrom:
        secretKeyRef:
          key: thanos.yaml
          name: thanos-objstore-config
    image: improbable/thanos:v0.4.0
    name: thanos-store-gateway
    ports:
    - containerPort: 10902
      name: http
      protocol: TCP
    - containerPort: 10901
      name: grpc
      protocol: TCP
    - containerPort: 10900
      name: cluster
      protocol: TCP
```

</p>
</details>

Service
<details>
<p>

```yaml
apiVersion: v1
kind: Service
metadata:
  name: thanos-store-grpc
  namespace: monitoring
  labels:
    app: thanos-store-gateway
spec:
  type: ClusterIP
  ports:
  - port: 10901
    targetPort: grpc
    protocol: TCP
    name: grpc
  selector:
    app: thanos-store-gateway
```

</p>
</details>

**Thanos query setup**
Deployment
<details>
<p>

```yaml
...
  containers:
  - args:
    - query
    - --log.level=debug
    - --query.replica-label=prometheus_replica
    - --cluster.disable
    - --store=thanos-store-grpc:10901
    - --store=thanos-sidecar-0:10901
    - --store=thanos-sidecar-1:10901
    image: improbable/thanos:v0.4.0
    name: thanos-query
    ports:
    - containerPort: 10902
      name: http
      protocol: TCP
    - containerPort: 10901
      name: grpc
      protocol: TCP
    - containerPort: 10900
      name: cluster
      protocol: TCP
```

</p>
</details>

**Full logs to relevant components**

Sidecar Logs
<details>
<p>

```
level=info ts=2019-05-22T17:35:38.017499041Z caller=flags.go:87 msg="gossip is disabled"
level=info ts=2019-05-22T17:35:38.017729042Z caller=main.go:257 component=sidecar msg="disabled TLS, key and cert must be set to enable"
level=info ts=2019-05-22T17:35:38.017757842Z caller=factory.go:39 msg="loading bucket configuration"
level=info ts=2019-05-22T17:35:38.190792929Z caller=sidecar.go:319 msg="starting sidecar" peer="no gossip"
level=info ts=2019-05-22T17:35:38.19096723Z caller=sidecar.go:260 component=sidecar msg="Listening for StoreAPI gRPC" address=[10.244.8.12]:10901
level=info ts=2019-05-22T17:35:38.19102123Z caller=main.go:309 msg="Listening for metrics" address=0.0.0.0:10902
level=warn ts=2019-05-22T17:35:38.19125663Z caller=sidecar.go:146 msg="failed to get Prometheus version. Is Prometheus running? Retrying" err="request version against http://127.0.0.1:9090/version: Get http://127.0.0.1:9090/version: dial tcp 127.0.0.1:9090: connect: connection refused"
level=info ts=2019-05-22T17:35:38.191342431Z caller=reloader.go:154 component=reloader msg="started watching config file and non-recursively rule dirs for changes" cfg= out= dirs=
level=info ts=2019-05-22T17:35:40.19971164Z caller=sidecar.go:176 msg="successfully loaded prometheus external labels" external_labels="{cluster=\"azure-production\",prometheus=\"monitoring/prometheus-operator-prometheus\",prometheus_replica=\"prometheus-prometheus-operator-prometheus-0\"}"
level=info ts=2019-05-22T20:36:08.354202158Z caller=shipper.go:350 msg="upload new block" id=01DBGM3JKJFB3P0H7HHMDRRM8H
```

</p>
</details>

Store Gateway Logs
<details>
<p>

```
level=info ts=2019-05-22T17:19:40.416942Z caller=flags.go:87 msg="gossip is disabled"
level=info ts=2019-05-22T17:19:40.4169811Z caller=factory.go:39 msg="loading bucket configuration"
level=debug ts=2019-05-22T17:19:40.417121701Z caller=azure.go:62 msg="creating new Azure bucket connection" component=store
level=debug ts=2019-05-22T17:19:40.626214962Z caller=azure.go:81 msg="Getting connection to existing Azure blob container" container=azure-production
level=info ts=2019-05-22T17:19:40.651121265Z caller=cache.go:172 msg="created index cache" maxItemSizeBytes=262144000 maxSizeBytes=524288000 maxItems=math.MaxInt64
level=debug ts=2019-05-22T17:19:40.651593567Z caller=store.go:152 msg="initializing bucket store"
level=debug ts=2019-05-22T17:19:40.679506282Z caller=store.go:156 msg="bucket store ready" init_duration=27.922416ms
level=info ts=2019-05-22T17:19:40.679721082Z caller=main.go:257 msg="disabled TLS, key and cert must be set to enable"
level=info ts=2019-05-22T17:19:40.679775183Z caller=store.go:221 msg="starting store node"
level=info ts=2019-05-22T17:19:40.679832783Z caller=store.go:190 msg="Listening for StoreAPI gRPC" address=0.0.0.0:10901
level=info ts=2019-05-22T17:19:40.679966383Z caller=main.go:309 msg="Listening for metrics" address=0.0.0.0:10902
level=debug ts=2019-05-22T20:37:40.84609301Z caller=azure.go:165 msg="getting blob" blob=01DBGM3JKJFB3P0H7HHMDRRM8H/meta.json offset=0 length=0
level=debug ts=2019-05-22T20:37:40.84611811Z caller=azure.go:165 msg="getting blob" blob=01DBGM3A7BV6YRF1J00T0QZXMN/meta.json offset=0 length=0
level=debug ts=2019-05-22T20:37:40.84615101Z caller=azure.go:222 msg="check if blob exists" blob=01DBGM3A7BV6YRF1J00T0QZXMN/meta.json
level=debug ts=2019-05-22T20:37:40.84613801Z caller=azure.go:222 msg="check if blob exists" blob=01DBGM3JKJFB3P0H7HHMDRRM8H/meta.json
level=debug ts=2019-05-22T20:37:41.023376566Z caller=azure.go:165 msg="getting blob" blob=01DBGM3A7BV6YRF1J00T0QZXMN/index.cache.json offset=0 length=0
level=debug ts=2019-05-22T20:37:41.023458866Z caller=azure.go:222 msg="check if blob exists" blob=01DBGM3A7BV6YRF1J00T0QZXMN/index.cache.json
level=debug ts=2019-05-22T20:37:41.047741329Z caller=azure.go:165 msg="getting blob" blob=01DBGM3A7BV6YRF1J00T0QZXMN/index offset=0 length=0
level=debug ts=2019-05-22T20:37:41.047767229Z caller=azure.go:222 msg="check if blob exists" blob=01DBGM3A7BV6YRF1J00T0QZXMN/index
level=debug ts=2019-05-22T20:37:41.066069476Z caller=azure.go:165 msg="getting blob" blob=01DBGM3JKJFB3P0H7HHMDRRM8H/index.cache.json offset=0 length=0
level=debug ts=2019-05-22T20:37:41.066095876Z caller=azure.go:222 msg="check if blob exists" blob=01DBGM3JKJFB3P0H7HHMDRRM8H/index.cache.json
level=debug ts=2019-05-22T20:37:41.119701914Z caller=azure.go:165 msg="getting blob" blob=01DBGM3JKJFB3P0H7HHMDRRM8H/index offset=0 length=0
level=debug ts=2019-05-22T20:37:41.119737014Z caller=azure.go:222 msg="check if blob exists" blob=01DBGM3JKJFB3P0H7HHMDRRM8H/index
```

</p>
</details>

Querier Logs
<details>
<p>

```
level=info ts=2019-05-22T17:45:30.641127736Z caller=flags.go:87 msg="gossip is disabled"
level=info ts=2019-05-22T17:45:30.644108442Z caller=main.go:257 component=query msg="disabled TLS, key and cert must be set to enable"
level=info ts=2019-05-22T17:45:30.644151542Z caller=query.go:490 msg="starting query node"
level=info ts=2019-05-22T17:45:30.644262742Z caller=query.go:459 msg="Listening for query and metrics" address=0.0.0.0:10902
level=info ts=2019-05-22T17:45:30.644289142Z caller=query.go:482 component=query msg="Listening for StoreAPI gRPC" address=0.0.0.0:10901
level=warn ts=2019-05-22T17:45:45.644586624Z caller=storeset.go:316 component=storeset msg="update of store node failed" err="initial store client info fetch: rpc error: code = DeadlineExceeded desc = context deadline exceeded" address=thanos-sidecar-0:10901
level=warn ts=2019-05-22T17:45:45.644604424Z caller=storeset.go:316 component=storeset msg="update of store node failed" err="initial store client info fetch: rpc error: code = DeadlineExceeded desc = context deadline exceeded" address=thanos-store-grpc:10901
level=warn ts=2019-05-22T17:45:45.644606824Z caller=storeset.go:316 component=storeset msg="update of store node failed" err="initial store client info fetch: rpc error: code = DeadlineExceeded desc = context deadline exceeded" address=thanos-sidecar-1:10901
level=warn ts=2019-05-22T17:45:55.644823184Z caller=storeset.go:316 component=storeset msg="update of store node failed" err="initial store client info fetch: rpc error: code = DeadlineExceeded desc = context deadline exceeded" address=thanos-store-grpc:10901
level=warn ts=2019-05-22T17:45:55.644845384Z caller=storeset.go:316 component=storeset msg="update of store node failed" err="initial store client info fetch: rpc error: code = DeadlineExceeded desc = context deadline exceeded" address=thanos-sidecar-0:10901
level=warn ts=2019-05-22T17:45:55.644996384Z caller=storeset.go:316 component=storeset msg="update of store node failed" err="initial store client info fetch: rpc error: code = DeadlineExceeded desc = context deadline exceeded" address=thanos-sidecar-1:10901
level=warn ts=2019-05-22T17:46:05.645196538Z caller=storeset.go:316 component=storeset msg="update of store node failed" err="initial store client info fetch: rpc error: code = DeadlineExceeded desc = context deadline exceeded" address=thanos-sidecar-1:10901
level=warn ts=2019-05-22T17:46:05.645196338Z caller=storeset.go:316 component=storeset msg="update of store node failed" err="initial store client info fetch: rpc error: code = DeadlineExceeded desc = context deadline exceeded" address=thanos-sidecar-0:10901
level=warn ts=2019-05-22T17:46:05.645240838Z caller=storeset.go:316 component=storeset msg="update of store node failed" err="initial store client info fetch: rpc error: code = DeadlineExceeded desc = context deadline exceeded" address=thanos-store-grpc:10901
```

</p>
</details>
