### ISSUE TITLE
Sidecar: no supported bucket was configured, uploads will be disabled

### ISSUE THREAD

**Issue by MaxDiOrio** [improbable-eng/thanos#1195]
Using latest releases of Prometheus-Operator and Thanos Sidecar (v0.4.0

**What happened** - Launched Prom Op with a Thanos Sidecar and receive the following error in the sidecar:  caller=sidecar.go:123 msg="no supported bucket was configured, uploads will be disabled" 

**What you expected to happen**. The sidecar would connect to the S3 compatible Object Storage

**How to reproduce it (as minimally and precisely as possible)**:

Have the following in the Prometheus Operator values yaml file:

```
    thanos:
      baseImage: improbable/thanos
      version: v0.4.0
      peers: thanos-peers.prod.cluster:10900
      objectStorageConfig:
        key: bucket.yaml
        name: thanos-objstore-config
```

I have a secret name thanos-objstore-config in the same namespace with a key bucket.yaml and value:

```
type: S3
config:
  endpoint: "minioingress.rook-minio.10.85.166.33.xip.io"
  bucket: "thanos"
  access_key: "MINIO_Access_Key"
  secret_key: "MINIO_Secret_Key"
  insecure: true
  signature_version2: false
```

The actual Thanos Store container has no problems with the bucket config used to access this same bucket.
