### ISSUE TITLE
Thanos image update

### ISSUE THREAD

**Issue by V3ckt0r** [improbable-eng/thanos#227]
Hey @Bplotka @fabxc,

I'm using the following to stand up a thanos store gateway

```
apiVersion: apps/v1beta1
kind: StatefulSet
metadata:
  name: thanos-store
spec:
  serviceName: "thanos-store"
  replicas: 1
  selector:
    matchLabels:
      app: thanos
      thanos-peer: "true"
  template:
    metadata:
      labels:
        app: thanos
        thanos-peer: "true"
    spec:
      containers:
      - name: thanos-store
        image: improbable/thanos:latest
        env:
        - name: SECRET_ACCESS
          valueFrom:
            secretKeyRef:
              name: secret-s3
              key: secret_access_s3
        - name: SECRET_KEY
          valueFrom:
            secretKeyRef:
              name: secret-s3
              key: secret_key_s3
        args:
        - "store"
        - "--log.level=debug"
        - "--tsdb.path=/var/thanos/store"
        - "--cluster.peers=thanos-peers.default.svc.cluster.local:10900"
        - "--s3.bucket=<bucket_name>"
        - "--s3.endpoint=s3-<az>.amazonaws.com"
        - "--s3.access-key=$(SECRET_ACCESS)"
        - "--s3.secret-key=$(SECRET_KEY)"
        ports:
        - name: http
          containerPort: 10902
        - name: grpc
          containerPort: 10901
        - name: cluster
          containerPort: 10900
        volumeMounts:
        - name: data
          mountPath: /var/thanos/store
      volumes:
      - name: data
        emptyDir: {}
```
However the image is failing to spin up:
```
Error parsing commandline arguments: required flag --gcs.bucket not provided
usage: thanos store --gcs.bucket=<bucket> [<flags>]
```

I suspect the improbable/thanos:latest image hasn't been updated and is an older image, as I can see in the master branch that the `--gcs.bucket` flag has been changed so it is no longer `Required()`

```
// registerStore registers a store command.
func registerStore(m map[string]setupFunc, app *kingpin.Application, name string) {
	cmd := app.Command(name, "store node giving access to blocks in a GCS bucket")

	grpcAddr := cmd.Flag("grpc-address", "listen address for gRPC endpoints").
		Default(defaultGRPCAddr).String()

	httpAddr := cmd.Flag("http-address", "listen address for HTTP endpoints").
		Default(defaultHTTPAddr).String()

	dataDir := cmd.Flag("tsdb.path", "data directory of TSDB").
		Default("./data").String()

	gcsBucket := cmd.Flag("gcs.bucket", "Google Cloud Storage bucket name for stored blocks. If empty sidecar won't store any block inside Google Cloud Storage").
		PlaceHolder("<bucket>").String()

```
