### ISSUE TITLE
store: Thanos store consumes almost 100G of memory at startup

### ISSUE THREAD

**Issue by mihailgmihaylov** [improbable-eng/thanos#325]
We have a strange issue with the memory consumption of Thanos Store in our Thanos setup.
Currently, we have a working setup of Prometheus and alertmanager as follows:
- 3 Prometheus 2.2.1 pods (in a statefulSet) with TSDB as backend. Docker image: `quay.io/prometheus/prometheus:v2.2.1`. Each Prometheus pod has a thanos sidecar. The docker image of the sidecar is: `improbable/thanos:master` (image id `2950dff67c9a`).
- 3 Alertmanager v0.15 pods (in a cluster). Docker image: `quay.io/prometheus/alertmanager:v0.15.0-rc.1`
- 2 Thanos Query pods.
The kubernetes server is running on AWS EC2 instances with S3 object storage as Thanos storage.

I am trying to implement the thanos-store, however, there is a very strange issue with memory consumption there.
We started a prometheus server from scratch 7d ago. Each prometheus pod consumes on avarage 1G of memory:
![prom-beforethanos-7d-data-on-demo-test](https://user-images.githubusercontent.com/19683080/39761545-116e42ca-52e1-11e8-9c91-ae16c289d380.png)

When I start the thanos-store and include it in the thanos cluster, the memory consumption is rocket high for the thanos-store.
It starts from 0 and consumes almost all resources on the node and finishes with OEMKill:
![prom-thanos-store-7d-data-on-demo-test](https://user-images.githubusercontent.com/19683080/39760451-ff121ca8-52dd-11e8-9992-19da6c0686aa.png)
After dedicating one 122G node only for thanos-store, I managed to fit the pot in. After the initial burst of memory, the memory eventually settles on about 60G and stays there:
![prom-thanos-store-7d-data-on-demo-test-120gnode](https://user-images.githubusercontent.com/19683080/39760611-692f7428-52de-11e8-8189-1322daed5a0a.png)

I changed some options like `storage.tsdb.retention` which was 30d to 24h and `chunk-pool-size` (from 2g to 512MB) but without any effect.

Here is some detailed information about our configuration:
Store:
```
      - name: thanos-store
        image: improbable/thanos:master
        env:
        - name: S3_ACCESS_KEY
          value: '***'
        - name: S3_SECRET_KEY
          value: '***'
        - name: S3_BUCKET
          value: '***'
        - name: S3_ENDPOINT
          value: 's3.eu-west-1.amazonaws.com'
        args:
        - "store"
        - "--log.level=debug"
        - "--tsdb.path=/var/thanos/store"
        - "--cluster.peers=monitoring-thanos-peers:10900"
        - "--chunk-pool-size=512MB"
        - "--index-cache-size=64MB"
```
Prometheus:
```
      - name: prometheus
        image: quay.io/prometheus/prometheus:v2.2.1
        args:
          - '--storage.tsdb.retention=24h'
          - '--storage.tsdb.no-lockfile'
          - '--storage.tsdb.path=/prometheus/data'
          - '--storage.tsdb.min-block-duration=2h'
          - '--storage.tsdb.max-block-duration=2h'
          - '--config.file=/etc/prometheus-shared/prometheus.yml'
          - '--web.enable-admin-api'
          - '--web.enable-lifecycle'
          - '--web.route-prefix=/'
```
Sidecar:
```
      - name: thanos-sidecar
        image: improbable/thanos:master
        env:
        - name: S3_ACCESS_KEY
          value: '***'
        - name: S3_SECRET_KEY
          value: '***'
        - name: S3_BUCKET
          value: '***'
        - name: S3_ENDPOINT
          value: 's3.eu-west-1.amazonaws.com'
        args:
        - "sidecar"
        - "--tsdb.path=/prometheus/data"
        - "--prometheus.url=http://localhost:9090"
        - "--cluster.peers=monitoring-thanos-peers:10900"
        - "--reloader.config-file=/etc/prometheus/prometheus.yml.tmpl"
        - "--reloader.config-envsubst-file=/etc/prometheus-shared/prometheus.yml"
```

I cannot see anything important that can give us meaningful information in thanos-sidecar logs:
```
level=debug ts=2018-05-08T13:11:22.604134111Z caller=cluster.go:117 msg="resolved peers to following addresses" peers=100.108.0.9:10900,100.112.0.7:10900,100.122.0.6:10900,100.122.0.9:10900,100.108.0.4:10900
level=debug ts=2018-05-08T13:11:22.611780542Z caller=store.go:147 msg="initializing bucket store"
level=debug ts=2018-05-08T13:18:16.247390978Z caller=store.go:151 msg="bucket store ready" init_duration=6m53.635610515s
level=info ts=2018-05-08T13:18:16.247636366Z caller=store.go:224 msg="starting store node"
level=debug ts=2018-05-08T13:18:16.252193094Z caller=delegate.go:82 component=cluster received=NotifyJoin node=01CCZY1EQKVGH5Y9A7BSTV80NP addr=100.119.0.4:10900
level=debug ts=2018-05-08T13:18:16.258597094Z caller=delegate.go:82 component=cluster received=NotifyJoin node=01CCZRRJQX37W64W2V0BYH9QG6 addr=100.108.0.4:10900
level=debug ts=2018-05-08T13:18:16.258640807Z caller=delegate.go:82 component=cluster received=NotifyJoin node=01CCZRRQWC61PSNSENQZR4M0M2 addr=100.122.0.9:10900
level=debug ts=2018-05-08T13:18:16.258661307Z caller=delegate.go:82 component=cluster received=NotifyJoin node=01CCZWET40SSP0VNGP0PVY247G addr=100.112.0.7:10900
level=debug ts=2018-05-08T13:18:16.258690371Z caller=delegate.go:82 component=cluster received=NotifyJoin node=01CCZWPM08E2TMT7A2NQ2KXRGK addr=100.108.0.9:10900
level=debug ts=2018-05-08T13:18:16.258727886Z caller=delegate.go:82 component=cluster received=NotifyJoin node=01CCZWXS7TRT7DC9XHQEBXPJCG addr=100.122.0.6:10900
level=debug ts=2018-05-08T13:18:16.268763726Z caller=cluster.go:201 component=cluster msg="joined cluster" peers=6
```

The sidecar logs are showing warnings, but I found out that this was due to the fact that prometheus took 1m to load. In the period which prometheus is loading, the sidecar cannot get the configuration from `api/v1/status/config` and issues this logs:
```
level=info ts=2018-05-08T12:43:43.105302282Z caller=sidecar.go:315 msg="starting sidecar" peer=
level=info ts=2018-05-08T12:43:43.105425435Z caller=reloader.go:77 component=reloader msg="started watching config file for changes" in=/etc/prometheus/prometheus.yml.tmpl out=/etc/prometheus-shared/prometheus.yml
level=warn ts=2018-05-08T12:43:43.112071103Z caller=sidecar.go:144 msg="failed to fetch initial external labels. Is Prometheus running? Retrying" err="decode response: invalid character 'S' looking for beginning of value"
level=warn ts=2018-05-08T12:43:45.106530306Z caller=sidecar.go:144 msg="failed to fetch initial external labels. Is Prometheus running? Retrying" err="decode response: invalid character 'S' looking for beginning of value"
level=warn ts=2018-05-08T12:43:47.106532299Z caller=sidecar.go:144 msg="failed to fetch initial external labels. Is Prometheus running? Retrying" err="decode response: invalid character 'S' looking for beginning of value"
level=warn ts=2018-05-08T12:43:49.106570044Z caller=sidecar.go:144 msg="failed to fetch initial external labels. Is Prometheus running? Retrying" err="decode response: invalid character 'S' looking for beginning of value"
level=warn ts=2018-05-08T12:43:51.168940045Z caller=sidecar.go:144 msg="failed to fetch initial external labels. Is Prometheus running? Retrying" err="decode response: invalid character 'S' looking for beginning of value"
level=warn ts=2018-05-08T12:43:53.168366187Z caller=sidecar.go:144 msg="failed to fetch initial external labels. Is Prometheus running? Retrying" err="decode response: invalid character 'S' looking for beginning of value"
level=warn ts=2018-05-08T12:43:55.10644909Z caller=sidecar.go:144 msg="failed to fetch initial external labels. Is Prometheus running? Retrying" err="decode response: invalid character 'S' looking for beginning of value"
level=warn ts=2018-05-08T12:43:57.168280363Z caller=sidecar.go:144 msg="failed to fetch initial external labels. Is Prometheus running? Retrying" err="decode response: invalid character 'S' looking for beginning of value"
level=warn ts=2018-05-08T12:43:59.106533152Z caller=sidecar.go:144 msg="failed to fetch initial external labels. Is Prometheus running? Retrying" err="decode response: invalid character 'S' looking for beginning of value"
level=info ts=2018-05-08T12:44:00.908563252Z caller=reloader.go:180 component=reloader msg="Prometheus reload triggered" cfg_in=/etc/prometheus/prometheus.yml.tmpl cfg_out=/etc/prometheus-shared/prometheus.yml rule_dir=
level=info ts=2018-05-08T13:00:13.188416171Z caller=shipper.go:185 msg="upload new block" id=01CCZXCMDGN4AM8G8MTB6F9DX7
```

Finally, the tsdb samples are not that many and therefore this overuse of memory is definitely not OK:
![prom-thanos-store-7d-data-on-demo-test-tsdb](https://user-images.githubusercontent.com/19683080/39761781-a9b3a822-52e1-11e8-9ca1-999af554d63b.png)

Any help would be appreciated!
I am very eager to make it work since it is a great tool!
