### ISSUE TITLE
Thanos Query returning no points when there are points in all prometheus replicas

### ISSUE THREAD

**Issue by felipejfc** [improbable-eng/thanos#344]
Hi, I'm running prometheus with the operator and trying to get thanos working, but query is being unreliable, returning no results, it generally works for like 3 minutes when I restart everything (prometheus + thanos-query) but then it starts returning empty values again, these are my manifests:

prometheus + sidecar statefulset:

```
apiVersion: apps/v1
kind: StatefulSet
metadata:
  labels:
    prometheus: k8s
  name: prometheus-k8s
  namespace: monitoring
spec:
  replicas: 3
  selector:
    matchLabels:
      app: prometheus
      prometheus: k8s
      thanos-peer: "true"
  serviceName: prometheus-operated
  template:
    metadata:
      labels:
        app: prometheus
        prometheus: k8s
        thanos-peer: "true"
    spec:
      containers:
      - args:
        - --config.file=/etc/prometheus/config_out/prometheus.env.yaml
        - --storage.tsdb.path=/prometheus
        - --storage.tsdb.retention=48h
        - --web.enable-lifecycle
        - --storage.tsdb.no-lockfile
        - --web.route-prefix=/
        image: quay.io/prometheus/prometheus:v2.2.1
        imagePullPolicy: IfNotPresent
        livenessProbe:
          failureThreshold: 6
          httpGet:
            path: /-/healthy
            port: web
            scheme: HTTP
          periodSeconds: 5
          successThreshold: 1
          timeoutSeconds: 3
        name: prometheus
        ports:
        - containerPort: 9090
          name: web
          protocol: TCP
        readinessProbe:
          failureThreshold: 120
          httpGet:
            path: /-/ready
            port: web
            scheme: HTTP
          periodSeconds: 5
          successThreshold: 1
          timeoutSeconds: 3
        resources:
          limits:
            cpu: "4"
            memory: 8G
          requests:
            cpu: "2"
            memory: 8G
        volumeMounts:
        - mountPath: /etc/prometheus/config_out
          name: config-out
          readOnly: true
        - mountPath: /prometheus
          name: prometheus-k8s-db
      - args:
        - --reload-url=http://localhost:9090/-/reload
        - --config-file=/etc/prometheus/config/prometheus.yaml
        - --rule-list-file=/etc/prometheus/config/configmaps.json
        - --config-envsubst-file=/etc/prometheus/config_out/prometheus.env.yaml
        - --rule-dir=/etc/prometheus/config_out/rules
        env:
        - name: POD_NAME
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.name
        image: quay.io/coreos/prometheus-config-reloader:v0.0.4
        imagePullPolicy: IfNotPresent
        name: prometheus-config-reloader
        resources:
          limits:
            cpu: 10m
            memory: 50Mi
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /etc/prometheus/config
          name: config
        - mountPath: /etc/prometheus/config_out
          name: config-out
      - args:
        - sidecar
        - --log.level=debug
        - --tsdb.path=/prometheus
        - --prometheus.url=http://127.0.0.1:9090
        - --cluster.peers=thanos-peers.monitoring.svc.cluster.local:10900
        env:
        image: improbable/thanos:v0.1.0-rc.0
        name: thanos
        ports:
        - containerPort: 10902
          name: http
          protocol: TCP
        - containerPort: 10901
          name: grpc
          protocol: TCP
        - containerPort: 10900
          name: cluster
          protocol: TCP
        volumeMounts:
        - mountPath: /prometheus
          name: prometheus-k8s-db
      dnsPolicy: ClusterFirst
      nodeSelector:
        beta.kubernetes.io/os: linux
      serviceAccount: prometheus-k8s
      serviceAccountName: prometheus-k8s
      volumes:
      - name: config
        secret:
          defaultMode: 420
          secretName: prometheus-k8s
      - emptyDir: {}
        name: config-out
      - emptyDir: {}
        name: prometheus-k8s-db
```

thanos query:

```
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: monitoring
  name: thanos-query
  labels:
    app: thanos-query
    thanos-peer: "true"
spec:
  replicas: 2
  selector:
    matchLabels:
      app: thanos-query
      thanos-peer: "true"
  template:
    metadata:
      labels:
        app: thanos-query
        thanos-peer: "true"
    spec:
      serviceAccountName: prometheus-k8s
      containers:
      - name: thanos-query
        image: improbable/thanos:v0.1.0-rc.0
        args:
        - "query"
        - "--log.level=debug"
        - "--query.replica-label=prometheus_replica"
        - "--cluster.peers=thanos-peers.monitoring.svc.cluster.local:10900"
        ports:
        - name: http
          containerPort: 10902
        - name: grpc
          containerPort: 10901
        - name: cluster
          containerPort: 10900
```

peers service:
```
apiVersion: v1
kind: Service
metadata:
  name: thanos-peers
  namespace: monitoring
spec:
  type: ClusterIP
  clusterIP: None
  ports:
  - name: cluster
    port: 10900
    targetPort: cluster
  selector:
    thanos-peer: "true"
```

the same query always returns results if I query any prometheus replica directly but do not reply any points if I query thanos.
