### ISSUE TITLE
failed to fetch initial external labels

### ISSUE THREAD

**Issue by jackyym** [improbable-eng/thanos#422]
**Thanos, Prometheus and Golang version used**

I get error  like this "failed to fetch initial external labels...... json: cannot unmarshal number into Go value of type struct { Data struct { YAML string \"json:\\\"yaml\\\"\" } \"json:\\\"data\\\"\" }"

and my prometheus.yml  is:

```
global:
  scrape_interval:     "15s"
  evaluation_interval: "15s"

  # Attach  these labels to any time series or alerts when communicating with
  # external systems (federation, remote storage, Alertmanager).
  #external_labels:
  #    region: us-east
  #    monitor: "docker-host-alpha"
  #    replica: A

# Load and evaluate rules in this file every "evaluation_interval" seconds.
rule_files:
  - "alert.rules"

# A scrape configuration containing exactly one endpoint to scrape.
scrape_configs:
  - job_name: "nodeexporter"
    scrape_interval: "5s"
    static_configs:
      - targets: ["nodeexporter:9100","xxxx:9100"]

  - job_name: "cadvisor"
    scrape_interval: "5s"
    static_configs:
      - targets: ["cadvisor:8080"]

  - job_name: "prometheus"
    scrape_interval: "10s"
    static_configs:
      - targets: ["localhost:9090"]

  - job_name: "pushgateway"
    scrape_interval: "10s"
    honor_labels: true
    static_configs:
      - targets: ["pushgateway:9091"]

  - job_name: "airflow"
    scrape_interval: "10s"
    honor_labels: true
    static_configs:
      - targets: ["xxxxx:9112"]


alerting:
  alertmanagers:
  - scheme: "http"
    static_configs:
    - targets: 
      - "alertmanager:9093"

#  - job_name: "nginx"
#    scrape_interval: 10s
#    static_configs:
#      - targets: ["nginxexporter:9113"]

#  - job_name: "aspnetcore"
#    scrape_interval: 10s
#    static_configs:
#      - targets: ["eventlog-proxy:5000", "eventlog:5000"]
```

Anyone can help me solve this problem?

**What you expected to happen**

**How to reproduce it (as minimally and precisely as possible)**:

**Full logs to relevant components**

**Anything else we need to know**
