### ISSUE TITLE
A way to keep some secret variables for Objstore in safe

### ISSUE THREAD

**Issue by jojohappy** [improbable-eng/thanos#539]
Related discussion: [#500(comment)](https://github.com/improbable-eng/thanos/pull/500#issuecomment-424762129)

Merged PR #500 , we have used yaml file related the configuration of object store instead of some flags and env variables. If Thanos is integrated in Kubernetes, the yaml file as configmap will not be in secret. In safe, we should still give a way to setup some variables in secret such as the secret key for S3 in Kubernetes or any other infrastructure system.

/cc @bwplotka @xjewer

**Comment by bwplotka** [comment]
Yup, the envars might be the solution here, not yet sure how to nicecly embed this int code to make it clear what envvars are supported etc.

**Comment by bwplotka** [comment]
@jojohappy You were interested how adding pass YAML by `content` fixes this issue. Basically for kubernetes it is as easy now as:
```
  - args:
        - sidecar
        - --http-address=0.0.0.0:19190
        - --grpc-address=0.0.0.0:19090
        - --cluster.address=0.0.0.0:19390
        - |
          --objstore.config=type: S3
          config:
            bucket: thanos-alpha
            endpoint: <endpoint>
            access-key: $(S3_ACCESS_KEY)
            secret-key: $(S3_SECRET_KEY)
            [other fields]
        - --log.level=debug
       [.. other flags]
    env:
        - name: S3_ACCESS_KEY
          valueFrom:
            secretKeyRef:
              key: accessKey
              name: <secret name>
        - name: S3_SECRET_KEY
          valueFrom:
            secretKeyRef:
              key: secretKey
              name: <secret name>
```
