### ISSUE TITLE
Rule: add external labels of prometheus 

### ISSUE THREAD

**Issue by wklken** [improbable-eng/thanos#614]
**Thanos, Prometheus and Golang version used**

Prometheus: 2.4.3
Thanos v0.1.0

**What happened**

- 10+ k8s clusters
- one prometheus-operator(with thanos sidecar)  in each cluster
- the prometheus has external_labels: `cluster_id: '10000'`
- use thanos-ruler, with the rule

```yaml
    - name: general.rules
      rules:
      - alert: TargetDown
        annotations:
          message: '{{ $value }}% of the {{ $labels.job }} targets are down.'
        expr: 100 * (count(up == 0) BY (job) / count(up) BY (job)) > 10
        for: 10m
        labels:
          severity: warning
```
- when any of the clusters match the rule, on thanos-ruler: alerts, just got `TargetDown (1 active)` with labels: `alertname="TargetDown" job="kubelet" severity="warning"`
- the alertmanager, `/api/v1/alerts/groups` got 

```
          "alerts": [
            {
              "labels": {
                "alertname": "TargetDown",
                "job": "kubelet",
                "severity": "warning",
              },
              "annotations": {
                "message": "50% of the kubelet targets are down."
              },
              "startsAt": "2018-11-06T09:39:29.644233109Z",
              "endsAt": "0001-01-01T00:00:00Z",
              "generatorURL": "",
              "status": {
                "state": "active",
                "silencedBy": [],
                "inhibitedBy": []
              },
              "receivers": null,
              "fingerprint": "b7bf125fefa57dab"
            }
          ]
```

So, in the end, We can't figure out which cluster hitted the rule

**What you expected to happen**

Is possible to add the `external_labels` of the Prometheus instance into the rule alert info? or just I did make the config right?

After read the codes of Thanos, I found t https://github.com/improbable-eng/thanos/blob/master/cmd/thanos/rule.go#L609, It seems after the query from Prometheus instance, the labels with no more labels after `count by`.

each Prometheus address will eval all rules via this function, is this the right place to add the labels?

**How to reproduce it (as minimally and precisely as possible)**:

**Full logs to relevant components**

**Anything else we need to know**

Thanks :)
