### ISSUE TITLE
thanos: command failed: create S3 client: insufficient s3 test configuration information

### ISSUE THREAD

**Issue by Alexvianet** [improbable-eng/thanos#674]
After thanos update to 0.2.0 version 

level=info ts=2018-12-12T13:00:24.302115433Z caller=factory.go:39 msg="loading bucket configuration"
compact command failed: create S3 client: insufficient s3 test configuration information
```
    exec thanos compact --wait \
      --objstore.config-file="/var/vcap/jobs/thanos_compactor/config/bucket_config.yaml" \
```
bucket_config.yaml
```
type: S3
config:
  bucket: "bucket-name"
  endpoint: "s3-endpoint"
  access_key: "access_key"
  insecure: false
  signature_version2: false
  encrypt_sse: false
  secret_key: "secret_key"
  http_config:
    idle_conn_timeout: 0s
```
thanos_compactor
log_level=debug

How to check what's a problem with configuration with 0.1.0 all works ok 
```
    export S3_SECRET_KEY="secret_key"
    exec thanos compact --wait \
      --s3.bucket="bucket-name" \
      --s3.endpoint="s3-endpoint" \
      --s3.access-key="access_key" \
```

same with thanos_store and sidecar
