### ISSUE TITLE
Can't query Thanos cluster through store-gateway

### ISSUE THREAD

**Issue by KarstenSiemer** [improbable-eng/thanos#872]
Hello,

currently I am trying to integrate thanos 0.3.1 into my prometheus 2.6.1 and prometheus-operator 0.29 setup.
There seem to be several issues with this.
Here is my prometheus crd:
```
apiVersion: monitoring.coreos.com/v1
kind: Prometheus
metadata:
  labels:
    app.kubernetes.io/instance: kube-prometheus
    app.kubernetes.io/name: prometheus
    app.kubernetes.io/version: v2.6.1
  name: kube-prometheus
  namespace: system-monitoring
spec:
  additionalScrapeConfigs:
    key: additional-scrape-configs.yaml
    name: kube-prometheus-config
  alerting:
    alertmanagers:
    - name: kube-alertmanager
      namespace: system-monitoring
      port: web
  baseImage: quay.io/prometheus/prometheus
  enableAdminAPI: true
  externalLabels:
    cluster: main
  externalUrl: https://xxxxxxx
  imagePullSecrets:
  - name: private-registry-auth-secret
  podMetadata:
    labels:
      app.kubernetes.io/component: prometheus
      app.kubernetes.io/instance: kube-prometheus
      app.kubernetes.io/name: prometheus
      app.kubernetes.io/version: v2.6.1
      thanos-store-api: "true"
  replicas: 2
  resources:
    limits:
      cpu: 1000m
      memory: 4Gi
    requests:
      cpu: 100m
      memory: 1536Mi
  retention: 20h
  ruleNamespaceSelector:
    matchLabels:
      prometheus.svc.y6b.de/evaluated-by: kube-prometheus
  ruleSelector:
    matchLabels:
      prometheus.svc.y6b.de/evaluated-by: kube-prometheus
  secrets:
  - prometheus-etcd-client-tls
  serviceAccountName: kube-prometheus
  serviceMonitorNamespaceSelector:
    matchLabels:
      prometheus.svc.y6b.de/scraped-by: kube-prometheus
  serviceMonitorSelector:
    matchLabels:
      prometheus.svc.y6b.de/scraped-by: kube-prometheus
  storage:
    volumeClaimTemplate:
      spec:
        resources:
          requests:
            storage: 100Gi
        storageClassName: rook-ceph-block-hdd
  thanos:
    baseImage: improbable/thanos
    objectStorageConfig:
      key: s3-config.yaml
      name: thanos-s3-config
    version: v0.3.1
  version: v2.6.1
```
Since the prometheus crd hasn't been updated to support thanos 0.3.1 to be able to disable gossip. It is activated. But that shouldn't be a problem or is it?

Thanos is reporting the following problem in it's log:
```
prometheus-kube-prometheus-0 thanos-sidecar level=warn ts=2019-02-27T08:57:16.560229262Z caller=sidecar.go:132 msg="failed to fetch initial external labels. Is Prometheus running? Retrying" err="is 'web.enable-admin-api' flag enabled? got non-200 response code: 503, response: Service Unavailable"
```

Even tough admin-api is activated and is reachable through 
http://localhost:9090/api/v1/status/config
(No authentication needed, the external url is for the ingress. but localhost can be accessed by localhost)

The sidecar itself is able to upload backup data into the s3.
It reports the upload in the log and i can verify the data in my s3

Also there are several external labels in my prometheus config.

The compactor is working as expected, it accesses the s3 and deduplicates etc...

The querier is not working, it finds the endpoint:
thanos-kube-store.system-monitoring.svc.main.y6b.de.:10901 | up
but if i query it can find a store for the metric:
No store matched for this query

This my headless service for my grpc endpoints:
```
apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/component: store
  name: thanos-kube-store
  namespace: system-monitoring
spec:
  ports:
  - name: thanos
    port: 10901
    protocol: TCP
    targetPort: grpc
  selector:
    thanos-store-api: "true"
```
This is the deployment from the store gateway:
```
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/component: store
    app.kubernetes.io/version: v0.3.1
  name: thanos-kube-store
  namespace: system-monitoring
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/component: store
  template:
    metadata:
      labels:
        app.kubernetes.io/component: store
        app.kubernetes.io/version: v0.3.1
        thanos-store-api: "true"
    spec:
      containers:
      - args:
        - store
        - --log.level=debug
        - --data-dir=/thanos-store-data
        - --cluster.disable
        - --index-cache-size=500MB
        - --chunk-pool-size=500MB
        - --objstore.config-file=/creds/s3-config.yaml
        image: improbable/thanos:master-2019-02-21-0c730c1
        name: thanos-store
        ports:
        - containerPort: 10902
          name: http
        - containerPort: 10901
          name: grpc
        resources:
          limits:
            cpu: 1
            memory: 2560Mi
          requests:
            cpu: 200m
            memory: 1536Mi
        volumeMounts:
        - mountPath: /thanos-store-data
          name: data
        - mountPath: /creds/
          name: s3-credentials
      imagePullSecrets:
      - name: private-registry-auth-secret
      volumes:
      - emptyDir: {}
        name: data
      - name: s3-credentials
        secret:
          defaultMode: 420
          secretName: thanos-s3-config
```
The querier:
```
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/component: querier
    app.kubernetes.io/version: v0.3.1
  name: thanos-querier
  namespace: system-monitoring
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/component: querier
  template:
    metadata:
      labels:
        app.kubernetes.io/component: querier
        app.kubernetes.io/version: v0.3.1
    spec:
      containers:
      - args:
        - query
        - --log.level=debug
        - --query.replica-label=prometheus_replica
        - --cluster.disable
        - --store=dnssrv+thanos-kube-store.system-monitoring.svc
        image: improbable/thanos:v0.3.1
        livenessProbe:
          httpGet:
            path: /-/healthy
            port: http
        name: thanos-querier
        ports:
        - containerPort: 10902
          name: http
        - containerPort: 10901
          name: grpc
        resources:
          limits:
            cpu: 1
            memory: 1536Mi
          requests:
            cpu: 350m
            memory: 512Mi
      imagePullSecrets:
      - name: private-registry-auth-secret
```
The headless service finds all peers:
```
→  kubectl describe svc thanos-kube-store
Name:              thanos-kube-store
Namespace:         system-monitoring
Labels:            app.kubernetes.io/component=store
Annotations:       kubectl.kubernetes.io/last-applied-configuration:
                     {"apiVersion":"v1","kind":"Service","metadata":{"annotations":{},"labels":{"app.kubernetes.io/component":"store"},"name":"thanos-kube-stor...
Selector:          thanos-store-api=true
Type:              ClusterIP
IP:                10.125.79.123
Port:              thanos  10901/TCP
TargetPort:        grpc/TCP
Endpoints:         10.248.10.112:10901,10.248.8.164:10901,10.248.9.107:10901
Session Affinity:  None
Events:            <none>
```
I tried editing the stateful set of prometheus and disable gossip for the thanos sidecar, but this didn't help.
What am i doing wrong here?

Kubernetes version: v1.13.2
thanos 0.3.1
prometheus: 2.6.1
operator: 0.29

**Comment by KarstenSiemer** [comment]
I have found the problem.
I configured the thanos-kube-store service wrong. I wasn't a headless service.
After recreating it as a headless service (ClusterIP: None). It's working

**Comment by boyka2405** [comment]
I am facing the similar issue but creating a headless service for thanos-storage gateway does not resolve the issue. Could you please let me know if there were any additional steps you performed to fix the issue.

In my case also querier can find the endpoint thanos-store-gateway-0.thanos-store-gateway.default.svc.cluster.local.:10901 but when it tries to query it does throws an error err="No store matched for this query"

It keeps on generating these logs continuously. Kindly help resolve the issue. @KarstenSiemer KarstenSiemer

**Comment by KarstenSiemer** [comment]
this is how i have it configured now:
in the querier pods:
```
...
- args:
    - query
    - --log.level=info
    - --query.replica-label=prometheus_replica
    - --cluster.disable
    - --query.auto-downsampling
    - --store=dnssrv+thanos-kube-store.system-monitoring.svc
...
```
and this is my service:
```
apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/component: store
    app.kubernetes.io/instance: thanos
  name: thanos-kube-store
  namespace: system-monitoring
spec:
  clusterIP: None
  ports:
  - name: thanos
    port: 10901
    protocol: TCP
    targetPort: grpc
  selector:
    thanos-store-api: "true"
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
```
